// Code generated by Fern. DO NOT EDIT.

package corpus

import (
	context "context"

	apgsdkgo "github.com/apologist-project/apg-sdk-go"
	core "github.com/apologist-project/apg-sdk-go/core"
	internal "github.com/apologist-project/apg-sdk-go/internal"
	option "github.com/apologist-project/apg-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Performs a semantic search across the agent's corpus of knowledge
//
// Example:
//
//	request := &apgsdkgo.CorpusSearchRequest{
//	    Query: "query",
//	}
//	client.Corpus.SearchCorpus(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) SearchCorpus(
	ctx context.Context,
	request *apgsdkgo.CorpusSearchRequest,
	opts ...option.RequestOption,
) (*apgsdkgo.SearchCorpusResponse, error) {
	response, err := c.WithRawResponse.SearchCorpus(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Records that a user viewed a specific corpus item
//
// Example:
//
//	request := &apgsdkgo.ViewRequest{
//	    Model: "model",
//	    ID: "id",
//	    PromptID: "prompt_id",
//	}
//	client.Corpus.LogCorpusView(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) LogCorpusView(
	ctx context.Context,
	request *apgsdkgo.ViewRequest,
	opts ...option.RequestOption,
) (*apgsdkgo.SuccessResponse, error) {
	response, err := c.WithRawResponse.LogCorpusView(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Records that a corpus item was shown to a user
//
// Example:
//
//	request := &apgsdkgo.ImpressionRequest{
//	    Model: "model",
//	    ID: "id",
//	    PromptID: "prompt_id",
//	}
//	client.Corpus.LogCorpusImpression(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) LogCorpusImpression(
	ctx context.Context,
	request *apgsdkgo.ImpressionRequest,
	opts ...option.RequestOption,
) (*apgsdkgo.SuccessResponse, error) {
	response, err := c.WithRawResponse.LogCorpusImpression(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Records a referral for a corpus item and, when a `url` is supplied, issues a 302 redirect to it. Without a `url`, responds with a success message. Requires either the search API entitlement or a same-origin request.
//
// Example:
//
//	request := &apgsdkgo.LogCorpusReferralRedirectRequest{
//	    Model: "model",
//	    ID: "id",
//	    PromptID: "prompt_id",
//	}
//	client.Corpus.LogCorpusReferralRedirect(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) LogCorpusReferralRedirect(
	ctx context.Context,
	request *apgsdkgo.LogCorpusReferralRedirectRequest,
	opts ...option.RequestOption,
) (*apgsdkgo.SuccessResponse, error) {
	response, err := c.WithRawResponse.LogCorpusReferralRedirect(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Records that a user was referred to a corpus item
//
// Example:
//
//	request := &apgsdkgo.ReferralRequest{
//	    Model: "model",
//	    ID: "id",
//	    PromptID: "prompt_id",
//	}
//	client.Corpus.LogCorpusReferral(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) LogCorpusReferral(
	ctx context.Context,
	request *apgsdkgo.ReferralRequest,
	opts ...option.RequestOption,
) (*apgsdkgo.SuccessResponse, error) {
	response, err := c.WithRawResponse.LogCorpusReferral(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
