// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/apologist-project/apg-sdk-go/internal"
	big "math/big"
)

// Agent-wide pause or resume result, including fan-out counts.
var (
	agentPauseStateFieldIsPaused  = big.NewInt(1 << 0)
	agentPauseStateFieldPausedAt  = big.NewInt(1 << 1)
	agentPauseStateFieldResumedAt = big.NewInt(1 << 2)
	agentPauseStateFieldEmitted   = big.NewInt(1 << 3)
	agentPauseStateFieldSkipped   = big.NewInt(1 << 4)
)

type AgentPauseState struct {
	IsPaused  *bool   `json:"is_paused,omitempty" url:"is_paused,omitempty"`
	PausedAt  *string `json:"paused_at,omitempty" url:"paused_at,omitempty"`
	ResumedAt *string `json:"resumed_at,omitempty" url:"resumed_at,omitempty"`
	// Conversations that received a transition message.
	Emitted *int `json:"emitted,omitempty" url:"emitted,omitempty"`
	// Conversations skipped during fan-out.
	Skipped *int `json:"skipped,omitempty" url:"skipped,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AgentPauseState) GetIsPaused() *bool {
	if a == nil {
		return nil
	}
	return a.IsPaused
}

func (a *AgentPauseState) GetPausedAt() *string {
	if a == nil {
		return nil
	}
	return a.PausedAt
}

func (a *AgentPauseState) GetResumedAt() *string {
	if a == nil {
		return nil
	}
	return a.ResumedAt
}

func (a *AgentPauseState) GetEmitted() *int {
	if a == nil {
		return nil
	}
	return a.Emitted
}

func (a *AgentPauseState) GetSkipped() *int {
	if a == nil {
		return nil
	}
	return a.Skipped
}

func (a *AgentPauseState) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AgentPauseState) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetIsPaused sets the IsPaused field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentPauseState) SetIsPaused(isPaused *bool) {
	a.IsPaused = isPaused
	a.require(agentPauseStateFieldIsPaused)
}

// SetPausedAt sets the PausedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentPauseState) SetPausedAt(pausedAt *string) {
	a.PausedAt = pausedAt
	a.require(agentPauseStateFieldPausedAt)
}

// SetResumedAt sets the ResumedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentPauseState) SetResumedAt(resumedAt *string) {
	a.ResumedAt = resumedAt
	a.require(agentPauseStateFieldResumedAt)
}

// SetEmitted sets the Emitted field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentPauseState) SetEmitted(emitted *int) {
	a.Emitted = emitted
	a.require(agentPauseStateFieldEmitted)
}

// SetSkipped sets the Skipped field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentPauseState) SetSkipped(skipped *int) {
	a.Skipped = skipped
	a.require(agentPauseStateFieldSkipped)
}

func (a *AgentPauseState) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentPauseState
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AgentPauseState(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AgentPauseState) MarshalJSON() ([]byte, error) {
	type embed AgentPauseState
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AgentPauseState) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	pauseAgentResponseFieldData = big.NewInt(1 << 0)
)

type PauseAgentResponse struct {
	Data *AgentPauseState `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PauseAgentResponse) GetData() *AgentPauseState {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PauseAgentResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PauseAgentResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PauseAgentResponse) SetData(data *AgentPauseState) {
	p.Data = data
	p.require(pauseAgentResponseFieldData)
}

func (p *PauseAgentResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PauseAgentResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PauseAgentResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PauseAgentResponse) MarshalJSON() ([]byte, error) {
	type embed PauseAgentResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PauseAgentResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	resumeAgentResponseFieldData = big.NewInt(1 << 0)
)

type ResumeAgentResponse struct {
	Data *AgentPauseState `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ResumeAgentResponse) GetData() *AgentPauseState {
	if r == nil {
		return nil
	}
	return r.Data
}

func (r *ResumeAgentResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *ResumeAgentResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ResumeAgentResponse) SetData(data *AgentPauseState) {
	r.Data = data
	r.require(resumeAgentResponseFieldData)
}

func (r *ResumeAgentResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ResumeAgentResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ResumeAgentResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ResumeAgentResponse) MarshalJSON() ([]byte, error) {
	type embed ResumeAgentResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ResumeAgentResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}
