// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersImpressionRequest(t *testing.T) {
	t.Run("SetModel", func(t *testing.T) {
		obj := &ImpressionRequest{}
		var fernTestValueModel string
		obj.SetModel(fernTestValueModel)
		assert.Equal(t, fernTestValueModel, obj.Model)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetID", func(t *testing.T) {
		obj := &ImpressionRequest{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPromptID", func(t *testing.T) {
		obj := &ImpressionRequest{}
		var fernTestValuePromptID string
		obj.SetPromptID(fernTestValuePromptID)
		assert.Equal(t, fernTestValuePromptID, obj.PromptID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUserID", func(t *testing.T) {
		obj := &ImpressionRequest{}
		var fernTestValueUserID *string
		obj.SetUserID(fernTestValueUserID)
		assert.Equal(t, fernTestValueUserID, obj.UserID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitImpressionRequest(t *testing.T) {
	t.Run("SetModel_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ImpressionRequest{}
		var fernTestValueModel string

		// Act
		obj.SetModel(fernTestValueModel)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ImpressionRequest{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPromptID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ImpressionRequest{}
		var fernTestValuePromptID string

		// Act
		obj.SetPromptID(fernTestValuePromptID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUserID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ImpressionRequest{}
		var fernTestValueUserID *string

		// Act
		obj.SetUserID(fernTestValueUserID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersReferralRequest(t *testing.T) {
	t.Run("SetModel", func(t *testing.T) {
		obj := &ReferralRequest{}
		var fernTestValueModel string
		obj.SetModel(fernTestValueModel)
		assert.Equal(t, fernTestValueModel, obj.Model)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetID", func(t *testing.T) {
		obj := &ReferralRequest{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPromptID", func(t *testing.T) {
		obj := &ReferralRequest{}
		var fernTestValuePromptID string
		obj.SetPromptID(fernTestValuePromptID)
		assert.Equal(t, fernTestValuePromptID, obj.PromptID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUserID", func(t *testing.T) {
		obj := &ReferralRequest{}
		var fernTestValueUserID *string
		obj.SetUserID(fernTestValueUserID)
		assert.Equal(t, fernTestValueUserID, obj.UserID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitReferralRequest(t *testing.T) {
	t.Run("SetModel_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReferralRequest{}
		var fernTestValueModel string

		// Act
		obj.SetModel(fernTestValueModel)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReferralRequest{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPromptID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReferralRequest{}
		var fernTestValuePromptID string

		// Act
		obj.SetPromptID(fernTestValuePromptID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUserID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReferralRequest{}
		var fernTestValueUserID *string

		// Act
		obj.SetUserID(fernTestValueUserID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersLogCorpusReferralRedirectRequest(t *testing.T) {
	t.Run("SetModel", func(t *testing.T) {
		obj := &LogCorpusReferralRedirectRequest{}
		var fernTestValueModel string
		obj.SetModel(fernTestValueModel)
		assert.Equal(t, fernTestValueModel, obj.Model)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetID", func(t *testing.T) {
		obj := &LogCorpusReferralRedirectRequest{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPromptID", func(t *testing.T) {
		obj := &LogCorpusReferralRedirectRequest{}
		var fernTestValuePromptID string
		obj.SetPromptID(fernTestValuePromptID)
		assert.Equal(t, fernTestValuePromptID, obj.PromptID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUserID", func(t *testing.T) {
		obj := &LogCorpusReferralRedirectRequest{}
		var fernTestValueUserID *string
		obj.SetUserID(fernTestValueUserID)
		assert.Equal(t, fernTestValueUserID, obj.UserID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetURL", func(t *testing.T) {
		obj := &LogCorpusReferralRedirectRequest{}
		var fernTestValueURL *string
		obj.SetURL(fernTestValueURL)
		assert.Equal(t, fernTestValueURL, obj.URL)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitLogCorpusReferralRedirectRequest(t *testing.T) {
	t.Run("SetModel_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &LogCorpusReferralRedirectRequest{}
		var fernTestValueModel string

		// Act
		obj.SetModel(fernTestValueModel)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &LogCorpusReferralRedirectRequest{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPromptID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &LogCorpusReferralRedirectRequest{}
		var fernTestValuePromptID string

		// Act
		obj.SetPromptID(fernTestValuePromptID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUserID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &LogCorpusReferralRedirectRequest{}
		var fernTestValueUserID *string

		// Act
		obj.SetUserID(fernTestValueUserID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &LogCorpusReferralRedirectRequest{}
		var fernTestValueURL *string

		// Act
		obj.SetURL(fernTestValueURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersViewRequest(t *testing.T) {
	t.Run("SetModel", func(t *testing.T) {
		obj := &ViewRequest{}
		var fernTestValueModel string
		obj.SetModel(fernTestValueModel)
		assert.Equal(t, fernTestValueModel, obj.Model)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetID", func(t *testing.T) {
		obj := &ViewRequest{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPromptID", func(t *testing.T) {
		obj := &ViewRequest{}
		var fernTestValuePromptID string
		obj.SetPromptID(fernTestValuePromptID)
		assert.Equal(t, fernTestValuePromptID, obj.PromptID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUserID", func(t *testing.T) {
		obj := &ViewRequest{}
		var fernTestValueUserID *string
		obj.SetUserID(fernTestValueUserID)
		assert.Equal(t, fernTestValueUserID, obj.UserID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitViewRequest(t *testing.T) {
	t.Run("SetModel_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ViewRequest{}
		var fernTestValueModel string

		// Act
		obj.SetModel(fernTestValueModel)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ViewRequest{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPromptID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ViewRequest{}
		var fernTestValuePromptID string

		// Act
		obj.SetPromptID(fernTestValuePromptID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUserID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ViewRequest{}
		var fernTestValueUserID *string

		// Act
		obj.SetUserID(fernTestValueUserID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCorpusSearchRequest(t *testing.T) {
	t.Run("SetQuery", func(t *testing.T) {
		obj := &CorpusSearchRequest{}
		var fernTestValueQuery string
		obj.SetQuery(fernTestValueQuery)
		assert.Equal(t, fernTestValueQuery, obj.Query)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPromptID", func(t *testing.T) {
		obj := &CorpusSearchRequest{}
		var fernTestValuePromptID *string
		obj.SetPromptID(fernTestValuePromptID)
		assert.Equal(t, fernTestValuePromptID, obj.PromptID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLimit", func(t *testing.T) {
		obj := &CorpusSearchRequest{}
		var fernTestValueLimit *int
		obj.SetLimit(fernTestValueLimit)
		assert.Equal(t, fernTestValueLimit, obj.Limit)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFilters", func(t *testing.T) {
		obj := &CorpusSearchRequest{}
		var fernTestValueFilters *CorpusSearchRequestFilters
		obj.SetFilters(fernTestValueFilters)
		assert.Equal(t, fernTestValueFilters, obj.Filters)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCorpusSearchRequest(t *testing.T) {
	t.Run("SetQuery_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequest{}
		var fernTestValueQuery string

		// Act
		obj.SetQuery(fernTestValueQuery)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPromptID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequest{}
		var fernTestValuePromptID *string

		// Act
		obj.SetPromptID(fernTestValuePromptID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLimit_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequest{}
		var fernTestValueLimit *int

		// Act
		obj.SetLimit(fernTestValueLimit)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFilters_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequest{}
		var fernTestValueFilters *CorpusSearchRequestFilters

		// Act
		obj.SetFilters(fernTestValueFilters)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCorpusSearchRequestFilters(t *testing.T) {
	t.Run("SetModel", func(t *testing.T) {
		obj := &CorpusSearchRequestFilters{}
		var fernTestValueModel *string
		obj.SetModel(fernTestValueModel)
		assert.Equal(t, fernTestValueModel, obj.Model)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIDs", func(t *testing.T) {
		obj := &CorpusSearchRequestFilters{}
		var fernTestValueIDs []int
		obj.SetIDs(fernTestValueIDs)
		assert.Equal(t, fernTestValueIDs, obj.IDs)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTypes", func(t *testing.T) {
		obj := &CorpusSearchRequestFilters{}
		var fernTestValueTypes []string
		obj.SetTypes(fernTestValueTypes)
		assert.Equal(t, fernTestValueTypes, obj.Types)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLanguages", func(t *testing.T) {
		obj := &CorpusSearchRequestFilters{}
		var fernTestValueLanguages []string
		obj.SetLanguages(fernTestValueLanguages)
		assert.Equal(t, fernTestValueLanguages, obj.Languages)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCollectionIDs", func(t *testing.T) {
		obj := &CorpusSearchRequestFilters{}
		var fernTestValueCollectionIDs []int
		obj.SetCollectionIDs(fernTestValueCollectionIDs)
		assert.Equal(t, fernTestValueCollectionIDs, obj.CollectionIDs)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetContributorIDs", func(t *testing.T) {
		obj := &CorpusSearchRequestFilters{}
		var fernTestValueContributorIDs []int
		obj.SetContributorIDs(fernTestValueContributorIDs)
		assert.Equal(t, fernTestValueContributorIDs, obj.ContributorIDs)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCategoryIDs", func(t *testing.T) {
		obj := &CorpusSearchRequestFilters{}
		var fernTestValueCategoryIDs []int
		obj.SetCategoryIDs(fernTestValueCategoryIDs)
		assert.Equal(t, fernTestValueCategoryIDs, obj.CategoryIDs)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetClassificationIDs", func(t *testing.T) {
		obj := &CorpusSearchRequestFilters{}
		var fernTestValueClassificationIDs []int
		obj.SetClassificationIDs(fernTestValueClassificationIDs)
		assert.Equal(t, fernTestValueClassificationIDs, obj.ClassificationIDs)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCorpusSearchRequestFilters(t *testing.T) {
	t.Run("GetModel", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}
		var expected *string
		obj.Model = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetModel(), "getter should return the property value")
	})

	t.Run("GetModel_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}
		obj.Model = nil

		// Act & Assert
		assert.Nil(t, obj.GetModel(), "getter should return nil when property is nil")
	})

	t.Run("GetModel_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CorpusSearchRequestFilters
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetModel() // Should return zero value
	})

	t.Run("GetIDs", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}
		var expected []int
		obj.IDs = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetIDs(), "getter should return the property value")
	})

	t.Run("GetIDs_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}
		obj.IDs = nil

		// Act & Assert
		assert.Nil(t, obj.GetIDs(), "getter should return nil when property is nil")
	})

	t.Run("GetIDs_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CorpusSearchRequestFilters
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetIDs() // Should return zero value
	})

	t.Run("GetTypes", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}
		var expected []string
		obj.Types = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTypes(), "getter should return the property value")
	})

	t.Run("GetTypes_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}
		obj.Types = nil

		// Act & Assert
		assert.Nil(t, obj.GetTypes(), "getter should return nil when property is nil")
	})

	t.Run("GetTypes_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CorpusSearchRequestFilters
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTypes() // Should return zero value
	})

	t.Run("GetLanguages", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}
		var expected []string
		obj.Languages = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLanguages(), "getter should return the property value")
	})

	t.Run("GetLanguages_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}
		obj.Languages = nil

		// Act & Assert
		assert.Nil(t, obj.GetLanguages(), "getter should return nil when property is nil")
	})

	t.Run("GetLanguages_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CorpusSearchRequestFilters
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLanguages() // Should return zero value
	})

	t.Run("GetCollectionIDs", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}
		var expected []int
		obj.CollectionIDs = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCollectionIDs(), "getter should return the property value")
	})

	t.Run("GetCollectionIDs_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}
		obj.CollectionIDs = nil

		// Act & Assert
		assert.Nil(t, obj.GetCollectionIDs(), "getter should return nil when property is nil")
	})

	t.Run("GetCollectionIDs_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CorpusSearchRequestFilters
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCollectionIDs() // Should return zero value
	})

	t.Run("GetContributorIDs", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}
		var expected []int
		obj.ContributorIDs = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetContributorIDs(), "getter should return the property value")
	})

	t.Run("GetContributorIDs_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}
		obj.ContributorIDs = nil

		// Act & Assert
		assert.Nil(t, obj.GetContributorIDs(), "getter should return nil when property is nil")
	})

	t.Run("GetContributorIDs_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CorpusSearchRequestFilters
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetContributorIDs() // Should return zero value
	})

	t.Run("GetCategoryIDs", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}
		var expected []int
		obj.CategoryIDs = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCategoryIDs(), "getter should return the property value")
	})

	t.Run("GetCategoryIDs_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}
		obj.CategoryIDs = nil

		// Act & Assert
		assert.Nil(t, obj.GetCategoryIDs(), "getter should return nil when property is nil")
	})

	t.Run("GetCategoryIDs_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CorpusSearchRequestFilters
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCategoryIDs() // Should return zero value
	})

	t.Run("GetClassificationIDs", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}
		var expected []int
		obj.ClassificationIDs = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetClassificationIDs(), "getter should return the property value")
	})

	t.Run("GetClassificationIDs_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}
		obj.ClassificationIDs = nil

		// Act & Assert
		assert.Nil(t, obj.GetClassificationIDs(), "getter should return nil when property is nil")
	})

	t.Run("GetClassificationIDs_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CorpusSearchRequestFilters
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetClassificationIDs() // Should return zero value
	})

}

func TestSettersMarkExplicitCorpusSearchRequestFilters(t *testing.T) {
	t.Run("SetModel_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}
		var fernTestValueModel *string

		// Act
		obj.SetModel(fernTestValueModel)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIDs_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}
		var fernTestValueIDs []int

		// Act
		obj.SetIDs(fernTestValueIDs)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTypes_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}
		var fernTestValueTypes []string

		// Act
		obj.SetTypes(fernTestValueTypes)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLanguages_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}
		var fernTestValueLanguages []string

		// Act
		obj.SetLanguages(fernTestValueLanguages)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCollectionIDs_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}
		var fernTestValueCollectionIDs []int

		// Act
		obj.SetCollectionIDs(fernTestValueCollectionIDs)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetContributorIDs_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}
		var fernTestValueContributorIDs []int

		// Act
		obj.SetContributorIDs(fernTestValueContributorIDs)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCategoryIDs_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}
		var fernTestValueCategoryIDs []int

		// Act
		obj.SetCategoryIDs(fernTestValueCategoryIDs)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetClassificationIDs_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}
		var fernTestValueClassificationIDs []int

		// Act
		obj.SetClassificationIDs(fernTestValueClassificationIDs)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersSearchCorpusResponse(t *testing.T) {
	t.Run("SetResults", func(t *testing.T) {
		obj := &SearchCorpusResponse{}
		var fernTestValueResults []map[string]any
		obj.SetResults(fernTestValueResults)
		assert.Equal(t, fernTestValueResults, obj.Results)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersSearchCorpusResponse(t *testing.T) {
	t.Run("GetResults", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SearchCorpusResponse{}
		var expected []map[string]any
		obj.Results = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetResults(), "getter should return the property value")
	})

	t.Run("GetResults_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SearchCorpusResponse{}
		obj.Results = nil

		// Act & Assert
		assert.Nil(t, obj.GetResults(), "getter should return nil when property is nil")
	})

	t.Run("GetResults_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SearchCorpusResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetResults() // Should return zero value
	})

}

func TestSettersMarkExplicitSearchCorpusResponse(t *testing.T) {
	t.Run("SetResults_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SearchCorpusResponse{}
		var fernTestValueResults []map[string]any

		// Act
		obj.SetResults(fernTestValueResults)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingCorpusSearchRequestFilters(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CorpusSearchRequestFilters{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CorpusSearchRequestFilters
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CorpusSearchRequestFilters
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CorpusSearchRequestFilters
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingSearchCorpusResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SearchCorpusResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled SearchCorpusResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj SearchCorpusResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj SearchCorpusResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringCorpusSearchRequestFilters(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CorpusSearchRequestFilters{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CorpusSearchRequestFilters
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringSearchCorpusResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &SearchCorpusResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SearchCorpusResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesCorpusSearchRequestFilters(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CorpusSearchRequestFilters{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CorpusSearchRequestFilters
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesSearchCorpusResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &SearchCorpusResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SearchCorpusResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
