// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/apologist-project/apg-sdk-go/internal"
	big "math/big"
)

var (
	impressionRequestFieldModel    = big.NewInt(1 << 0)
	impressionRequestFieldID       = big.NewInt(1 << 1)
	impressionRequestFieldPromptID = big.NewInt(1 << 2)
	impressionRequestFieldUserID   = big.NewInt(1 << 3)
)

type ImpressionRequest struct {
	// The model type (e.g., 'source')
	Model string `json:"-" url:"-"`
	// The ID of the corpus item
	ID       string  `json:"-" url:"-"`
	PromptID string  `json:"prompt_id" url:"-"`
	UserID   *string `json:"user_id,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *ImpressionRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetModel sets the Model field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImpressionRequest) SetModel(model string) {
	i.Model = model
	i.require(impressionRequestFieldModel)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImpressionRequest) SetID(id string) {
	i.ID = id
	i.require(impressionRequestFieldID)
}

// SetPromptID sets the PromptID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImpressionRequest) SetPromptID(promptID string) {
	i.PromptID = promptID
	i.require(impressionRequestFieldPromptID)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *ImpressionRequest) SetUserID(userID *string) {
	i.UserID = userID
	i.require(impressionRequestFieldUserID)
}

func (i *ImpressionRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler ImpressionRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*i = ImpressionRequest(body)
	return nil
}

func (i *ImpressionRequest) MarshalJSON() ([]byte, error) {
	type embed ImpressionRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	referralRequestFieldModel    = big.NewInt(1 << 0)
	referralRequestFieldID       = big.NewInt(1 << 1)
	referralRequestFieldPromptID = big.NewInt(1 << 2)
	referralRequestFieldUserID   = big.NewInt(1 << 3)
)

type ReferralRequest struct {
	// The model type (e.g., 'source')
	Model string `json:"-" url:"-"`
	// The ID of the corpus item
	ID       string  `json:"-" url:"-"`
	PromptID string  `json:"prompt_id" url:"-"`
	UserID   *string `json:"user_id,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ReferralRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetModel sets the Model field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferralRequest) SetModel(model string) {
	r.Model = model
	r.require(referralRequestFieldModel)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferralRequest) SetID(id string) {
	r.ID = id
	r.require(referralRequestFieldID)
}

// SetPromptID sets the PromptID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferralRequest) SetPromptID(promptID string) {
	r.PromptID = promptID
	r.require(referralRequestFieldPromptID)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReferralRequest) SetUserID(userID *string) {
	r.UserID = userID
	r.require(referralRequestFieldUserID)
}

func (r *ReferralRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler ReferralRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = ReferralRequest(body)
	return nil
}

func (r *ReferralRequest) MarshalJSON() ([]byte, error) {
	type embed ReferralRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	logCorpusReferralRedirectRequestFieldModel    = big.NewInt(1 << 0)
	logCorpusReferralRedirectRequestFieldID       = big.NewInt(1 << 1)
	logCorpusReferralRedirectRequestFieldPromptID = big.NewInt(1 << 2)
	logCorpusReferralRedirectRequestFieldUserID   = big.NewInt(1 << 3)
	logCorpusReferralRedirectRequestFieldURL      = big.NewInt(1 << 4)
)

type LogCorpusReferralRedirectRequest struct {
	// The model type (e.g., 'source')
	Model string `json:"-" url:"-"`
	// The numeric ID of the corpus item
	ID       string  `json:"-" url:"-"`
	PromptID string  `json:"-" url:"prompt_id"`
	UserID   *string `json:"-" url:"user_id,omitempty"`
	// URL-encoded destination to redirect to after logging the referral.
	URL *string `json:"-" url:"url,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *LogCorpusReferralRedirectRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetModel sets the Model field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LogCorpusReferralRedirectRequest) SetModel(model string) {
	l.Model = model
	l.require(logCorpusReferralRedirectRequestFieldModel)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LogCorpusReferralRedirectRequest) SetID(id string) {
	l.ID = id
	l.require(logCorpusReferralRedirectRequestFieldID)
}

// SetPromptID sets the PromptID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LogCorpusReferralRedirectRequest) SetPromptID(promptID string) {
	l.PromptID = promptID
	l.require(logCorpusReferralRedirectRequestFieldPromptID)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LogCorpusReferralRedirectRequest) SetUserID(userID *string) {
	l.UserID = userID
	l.require(logCorpusReferralRedirectRequestFieldUserID)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LogCorpusReferralRedirectRequest) SetURL(url *string) {
	l.URL = url
	l.require(logCorpusReferralRedirectRequestFieldURL)
}

var (
	viewRequestFieldModel    = big.NewInt(1 << 0)
	viewRequestFieldID       = big.NewInt(1 << 1)
	viewRequestFieldPromptID = big.NewInt(1 << 2)
	viewRequestFieldUserID   = big.NewInt(1 << 3)
)

type ViewRequest struct {
	// The model type (e.g., 'source')
	Model string `json:"-" url:"-"`
	// The ID of the corpus item
	ID       string  `json:"-" url:"-"`
	PromptID string  `json:"prompt_id" url:"-"`
	UserID   *string `json:"user_id,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *ViewRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetModel sets the Model field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ViewRequest) SetModel(model string) {
	v.Model = model
	v.require(viewRequestFieldModel)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ViewRequest) SetID(id string) {
	v.ID = id
	v.require(viewRequestFieldID)
}

// SetPromptID sets the PromptID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ViewRequest) SetPromptID(promptID string) {
	v.PromptID = promptID
	v.require(viewRequestFieldPromptID)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ViewRequest) SetUserID(userID *string) {
	v.UserID = userID
	v.require(viewRequestFieldUserID)
}

func (v *ViewRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler ViewRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*v = ViewRequest(body)
	return nil
}

func (v *ViewRequest) MarshalJSON() ([]byte, error) {
	type embed ViewRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	corpusSearchRequestFieldQuery    = big.NewInt(1 << 0)
	corpusSearchRequestFieldPromptID = big.NewInt(1 << 1)
	corpusSearchRequestFieldLimit    = big.NewInt(1 << 2)
	corpusSearchRequestFieldFilters  = big.NewInt(1 << 3)
)

type CorpusSearchRequest struct {
	Query    string                      `json:"query" url:"-"`
	PromptID *string                     `json:"prompt_id,omitempty" url:"-"`
	Limit    *int                        `json:"limit,omitempty" url:"-"`
	Filters  *CorpusSearchRequestFilters `json:"filters,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CorpusSearchRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CorpusSearchRequest) SetQuery(query string) {
	c.Query = query
	c.require(corpusSearchRequestFieldQuery)
}

// SetPromptID sets the PromptID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CorpusSearchRequest) SetPromptID(promptID *string) {
	c.PromptID = promptID
	c.require(corpusSearchRequestFieldPromptID)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CorpusSearchRequest) SetLimit(limit *int) {
	c.Limit = limit
	c.require(corpusSearchRequestFieldLimit)
}

// SetFilters sets the Filters field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CorpusSearchRequest) SetFilters(filters *CorpusSearchRequestFilters) {
	c.Filters = filters
	c.require(corpusSearchRequestFieldFilters)
}

func (c *CorpusSearchRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CorpusSearchRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CorpusSearchRequest(body)
	return nil
}

func (c *CorpusSearchRequest) MarshalJSON() ([]byte, error) {
	type embed CorpusSearchRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	corpusSearchRequestFiltersFieldModel             = big.NewInt(1 << 0)
	corpusSearchRequestFiltersFieldIDs               = big.NewInt(1 << 1)
	corpusSearchRequestFiltersFieldTypes             = big.NewInt(1 << 2)
	corpusSearchRequestFiltersFieldLanguages         = big.NewInt(1 << 3)
	corpusSearchRequestFiltersFieldCollectionIDs     = big.NewInt(1 << 4)
	corpusSearchRequestFiltersFieldContributorIDs    = big.NewInt(1 << 5)
	corpusSearchRequestFiltersFieldCategoryIDs       = big.NewInt(1 << 6)
	corpusSearchRequestFiltersFieldClassificationIDs = big.NewInt(1 << 7)
)

type CorpusSearchRequestFilters struct {
	Model             *string  `json:"model,omitempty" url:"model,omitempty"`
	IDs               []int    `json:"ids,omitempty" url:"ids,omitempty"`
	Types             []string `json:"types,omitempty" url:"types,omitempty"`
	Languages         []string `json:"languages,omitempty" url:"languages,omitempty"`
	CollectionIDs     []int    `json:"collection_ids,omitempty" url:"collection_ids,omitempty"`
	ContributorIDs    []int    `json:"contributor_ids,omitempty" url:"contributor_ids,omitempty"`
	CategoryIDs       []int    `json:"category_ids,omitempty" url:"category_ids,omitempty"`
	ClassificationIDs []int    `json:"classification_ids,omitempty" url:"classification_ids,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CorpusSearchRequestFilters) GetModel() *string {
	if c == nil {
		return nil
	}
	return c.Model
}

func (c *CorpusSearchRequestFilters) GetIDs() []int {
	if c == nil {
		return nil
	}
	return c.IDs
}

func (c *CorpusSearchRequestFilters) GetTypes() []string {
	if c == nil {
		return nil
	}
	return c.Types
}

func (c *CorpusSearchRequestFilters) GetLanguages() []string {
	if c == nil {
		return nil
	}
	return c.Languages
}

func (c *CorpusSearchRequestFilters) GetCollectionIDs() []int {
	if c == nil {
		return nil
	}
	return c.CollectionIDs
}

func (c *CorpusSearchRequestFilters) GetContributorIDs() []int {
	if c == nil {
		return nil
	}
	return c.ContributorIDs
}

func (c *CorpusSearchRequestFilters) GetCategoryIDs() []int {
	if c == nil {
		return nil
	}
	return c.CategoryIDs
}

func (c *CorpusSearchRequestFilters) GetClassificationIDs() []int {
	if c == nil {
		return nil
	}
	return c.ClassificationIDs
}

func (c *CorpusSearchRequestFilters) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CorpusSearchRequestFilters) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetModel sets the Model field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CorpusSearchRequestFilters) SetModel(model *string) {
	c.Model = model
	c.require(corpusSearchRequestFiltersFieldModel)
}

// SetIDs sets the IDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CorpusSearchRequestFilters) SetIDs(ids []int) {
	c.IDs = ids
	c.require(corpusSearchRequestFiltersFieldIDs)
}

// SetTypes sets the Types field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CorpusSearchRequestFilters) SetTypes(types []string) {
	c.Types = types
	c.require(corpusSearchRequestFiltersFieldTypes)
}

// SetLanguages sets the Languages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CorpusSearchRequestFilters) SetLanguages(languages []string) {
	c.Languages = languages
	c.require(corpusSearchRequestFiltersFieldLanguages)
}

// SetCollectionIDs sets the CollectionIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CorpusSearchRequestFilters) SetCollectionIDs(collectionIDs []int) {
	c.CollectionIDs = collectionIDs
	c.require(corpusSearchRequestFiltersFieldCollectionIDs)
}

// SetContributorIDs sets the ContributorIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CorpusSearchRequestFilters) SetContributorIDs(contributorIDs []int) {
	c.ContributorIDs = contributorIDs
	c.require(corpusSearchRequestFiltersFieldContributorIDs)
}

// SetCategoryIDs sets the CategoryIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CorpusSearchRequestFilters) SetCategoryIDs(categoryIDs []int) {
	c.CategoryIDs = categoryIDs
	c.require(corpusSearchRequestFiltersFieldCategoryIDs)
}

// SetClassificationIDs sets the ClassificationIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CorpusSearchRequestFilters) SetClassificationIDs(classificationIDs []int) {
	c.ClassificationIDs = classificationIDs
	c.require(corpusSearchRequestFiltersFieldClassificationIDs)
}

func (c *CorpusSearchRequestFilters) UnmarshalJSON(data []byte) error {
	type unmarshaler CorpusSearchRequestFilters
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CorpusSearchRequestFilters(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CorpusSearchRequestFilters) MarshalJSON() ([]byte, error) {
	type embed CorpusSearchRequestFilters
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CorpusSearchRequestFilters) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	searchCorpusResponseFieldResults = big.NewInt(1 << 0)
)

type SearchCorpusResponse struct {
	Results []map[string]any `json:"results,omitempty" url:"results,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SearchCorpusResponse) GetResults() []map[string]any {
	if s == nil {
		return nil
	}
	return s.Results
}

func (s *SearchCorpusResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SearchCorpusResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetResults sets the Results field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchCorpusResponse) SetResults(results []map[string]any) {
	s.Results = results
	s.require(searchCorpusResponseFieldResults)
}

func (s *SearchCorpusResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SearchCorpusResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SearchCorpusResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SearchCorpusResponse) MarshalJSON() ([]byte, error) {
	type embed SearchCorpusResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SearchCorpusResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
