// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersEvaluatorRequest(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &EvaluatorRequest{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFrequencyPenalty", func(t *testing.T) {
		obj := &EvaluatorRequest{}
		var fernTestValueFrequencyPenalty *float64
		obj.SetFrequencyPenalty(fernTestValueFrequencyPenalty)
		assert.Equal(t, fernTestValueFrequencyPenalty, obj.FrequencyPenalty)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetConfidenceThreshold", func(t *testing.T) {
		obj := &EvaluatorRequest{}
		var fernTestValueConfidenceThreshold *float64
		obj.SetConfidenceThreshold(fernTestValueConfidenceThreshold)
		assert.Equal(t, fernTestValueConfidenceThreshold, obj.ConfidenceThreshold)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetContent", func(t *testing.T) {
		obj := &EvaluatorRequest{}
		var fernTestValueContent *EvaluatorRequestContent
		obj.SetContent(fernTestValueContent)
		assert.Equal(t, fernTestValueContent, obj.Content)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetModel", func(t *testing.T) {
		obj := &EvaluatorRequest{}
		var fernTestValueModel *string
		obj.SetModel(fernTestValueModel)
		assert.Equal(t, fernTestValueModel, obj.Model)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPresencePenalty", func(t *testing.T) {
		obj := &EvaluatorRequest{}
		var fernTestValuePresencePenalty *float64
		obj.SetPresencePenalty(fernTestValuePresencePenalty)
		assert.Equal(t, fernTestValuePresencePenalty, obj.PresencePenalty)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetReasoningEffort", func(t *testing.T) {
		obj := &EvaluatorRequest{}
		var fernTestValueReasoningEffort *EvaluatorRequestReasoningEffort
		obj.SetReasoningEffort(fernTestValueReasoningEffort)
		assert.Equal(t, fernTestValueReasoningEffort, obj.ReasoningEffort)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetVerbosity", func(t *testing.T) {
		obj := &EvaluatorRequest{}
		var fernTestValueVerbosity *EvaluatorRequestVerbosity
		obj.SetVerbosity(fernTestValueVerbosity)
		assert.Equal(t, fernTestValueVerbosity, obj.Verbosity)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTemperature", func(t *testing.T) {
		obj := &EvaluatorRequest{}
		var fernTestValueTemperature *float64
		obj.SetTemperature(fernTestValueTemperature)
		assert.Equal(t, fernTestValueTemperature, obj.Temperature)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTopP", func(t *testing.T) {
		obj := &EvaluatorRequest{}
		var fernTestValueTopP *float64
		obj.SetTopP(fernTestValueTopP)
		assert.Equal(t, fernTestValueTopP, obj.TopP)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetVariables", func(t *testing.T) {
		obj := &EvaluatorRequest{}
		var fernTestValueVariables map[string]*string
		obj.SetVariables(fernTestValueVariables)
		assert.Equal(t, fernTestValueVariables, obj.Variables)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitEvaluatorRequest(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvaluatorRequest{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFrequencyPenalty_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvaluatorRequest{}
		var fernTestValueFrequencyPenalty *float64

		// Act
		obj.SetFrequencyPenalty(fernTestValueFrequencyPenalty)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetConfidenceThreshold_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvaluatorRequest{}
		var fernTestValueConfidenceThreshold *float64

		// Act
		obj.SetConfidenceThreshold(fernTestValueConfidenceThreshold)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetContent_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvaluatorRequest{}
		var fernTestValueContent *EvaluatorRequestContent

		// Act
		obj.SetContent(fernTestValueContent)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetModel_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvaluatorRequest{}
		var fernTestValueModel *string

		// Act
		obj.SetModel(fernTestValueModel)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPresencePenalty_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvaluatorRequest{}
		var fernTestValuePresencePenalty *float64

		// Act
		obj.SetPresencePenalty(fernTestValuePresencePenalty)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetReasoningEffort_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvaluatorRequest{}
		var fernTestValueReasoningEffort *EvaluatorRequestReasoningEffort

		// Act
		obj.SetReasoningEffort(fernTestValueReasoningEffort)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetVerbosity_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvaluatorRequest{}
		var fernTestValueVerbosity *EvaluatorRequestVerbosity

		// Act
		obj.SetVerbosity(fernTestValueVerbosity)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTemperature_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvaluatorRequest{}
		var fernTestValueTemperature *float64

		// Act
		obj.SetTemperature(fernTestValueTemperature)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTopP_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvaluatorRequest{}
		var fernTestValueTopP *float64

		// Act
		obj.SetTopP(fernTestValueTopP)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetVariables_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvaluatorRequest{}
		var fernTestValueVariables map[string]*string

		// Act
		obj.SetVariables(fernTestValueVariables)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetEvaluationRequest(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &GetEvaluationRequest{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEvaluationID", func(t *testing.T) {
		obj := &GetEvaluationRequest{}
		var fernTestValueEvaluationID string
		obj.SetEvaluationID(fernTestValueEvaluationID)
		assert.Equal(t, fernTestValueEvaluationID, obj.EvaluationID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetEvaluationRequest(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetEvaluationRequest{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEvaluationID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetEvaluationRequest{}
		var fernTestValueEvaluationID string

		// Act
		obj.SetEvaluationID(fernTestValueEvaluationID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListEvaluationsRequest(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &ListEvaluationsRequest{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPage", func(t *testing.T) {
		obj := &ListEvaluationsRequest{}
		var fernTestValuePage *int
		obj.SetPage(fernTestValuePage)
		assert.Equal(t, fernTestValuePage, obj.Page)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPerPage", func(t *testing.T) {
		obj := &ListEvaluationsRequest{}
		var fernTestValuePerPage *int
		obj.SetPerPage(fernTestValuePerPage)
		assert.Equal(t, fernTestValuePerPage, obj.PerPage)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMinTimestamp", func(t *testing.T) {
		obj := &ListEvaluationsRequest{}
		var fernTestValueMinTimestamp *string
		obj.SetMinTimestamp(fernTestValueMinTimestamp)
		assert.Equal(t, fernTestValueMinTimestamp, obj.MinTimestamp)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMaxTimestamp", func(t *testing.T) {
		obj := &ListEvaluationsRequest{}
		var fernTestValueMaxTimestamp *string
		obj.SetMaxTimestamp(fernTestValueMaxTimestamp)
		assert.Equal(t, fernTestValueMaxTimestamp, obj.MaxTimestamp)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMinDuration", func(t *testing.T) {
		obj := &ListEvaluationsRequest{}
		var fernTestValueMinDuration *string
		obj.SetMinDuration(fernTestValueMinDuration)
		assert.Equal(t, fernTestValueMinDuration, obj.MinDuration)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMaxDuration", func(t *testing.T) {
		obj := &ListEvaluationsRequest{}
		var fernTestValueMaxDuration *string
		obj.SetMaxDuration(fernTestValueMaxDuration)
		assert.Equal(t, fernTestValueMaxDuration, obj.MaxDuration)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMinScore", func(t *testing.T) {
		obj := &ListEvaluationsRequest{}
		var fernTestValueMinScore *string
		obj.SetMinScore(fernTestValueMinScore)
		assert.Equal(t, fernTestValueMinScore, obj.MinScore)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMaxScore", func(t *testing.T) {
		obj := &ListEvaluationsRequest{}
		var fernTestValueMaxScore *string
		obj.SetMaxScore(fernTestValueMaxScore)
		assert.Equal(t, fernTestValueMaxScore, obj.MaxScore)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPassed", func(t *testing.T) {
		obj := &ListEvaluationsRequest{}
		var fernTestValuePassed *string
		obj.SetPassed(fernTestValuePassed)
		assert.Equal(t, fernTestValuePassed, obj.Passed)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetBenchmark", func(t *testing.T) {
		obj := &ListEvaluationsRequest{}
		var fernTestValueBenchmark *string
		obj.SetBenchmark(fernTestValueBenchmark)
		assert.Equal(t, fernTestValueBenchmark, obj.Benchmark)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetBenchmarkRunID", func(t *testing.T) {
		obj := &ListEvaluationsRequest{}
		var fernTestValueBenchmarkRunID *string
		obj.SetBenchmarkRunID(fernTestValueBenchmarkRunID)
		assert.Equal(t, fernTestValueBenchmarkRunID, obj.BenchmarkRunID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetBenchmarkQuestionID", func(t *testing.T) {
		obj := &ListEvaluationsRequest{}
		var fernTestValueBenchmarkQuestionID *string
		obj.SetBenchmarkQuestionID(fernTestValueBenchmarkQuestionID)
		assert.Equal(t, fernTestValueBenchmarkQuestionID, obj.BenchmarkQuestionID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitListEvaluationsRequest(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsRequest{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsRequest{}
		var fernTestValuePage *int

		// Act
		obj.SetPage(fernTestValuePage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPerPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsRequest{}
		var fernTestValuePerPage *int

		// Act
		obj.SetPerPage(fernTestValuePerPage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMinTimestamp_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsRequest{}
		var fernTestValueMinTimestamp *string

		// Act
		obj.SetMinTimestamp(fernTestValueMinTimestamp)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMaxTimestamp_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsRequest{}
		var fernTestValueMaxTimestamp *string

		// Act
		obj.SetMaxTimestamp(fernTestValueMaxTimestamp)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMinDuration_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsRequest{}
		var fernTestValueMinDuration *string

		// Act
		obj.SetMinDuration(fernTestValueMinDuration)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMaxDuration_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsRequest{}
		var fernTestValueMaxDuration *string

		// Act
		obj.SetMaxDuration(fernTestValueMaxDuration)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMinScore_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsRequest{}
		var fernTestValueMinScore *string

		// Act
		obj.SetMinScore(fernTestValueMinScore)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMaxScore_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsRequest{}
		var fernTestValueMaxScore *string

		// Act
		obj.SetMaxScore(fernTestValueMaxScore)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPassed_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsRequest{}
		var fernTestValuePassed *string

		// Act
		obj.SetPassed(fernTestValuePassed)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetBenchmark_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsRequest{}
		var fernTestValueBenchmark *string

		// Act
		obj.SetBenchmark(fernTestValueBenchmark)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetBenchmarkRunID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsRequest{}
		var fernTestValueBenchmarkRunID *string

		// Act
		obj.SetBenchmarkRunID(fernTestValueBenchmarkRunID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetBenchmarkQuestionID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsRequest{}
		var fernTestValueBenchmarkQuestionID *string

		// Act
		obj.SetBenchmarkQuestionID(fernTestValueBenchmarkQuestionID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersEvaluateContentResponse(t *testing.T) {
	t.Run("SetResult", func(t *testing.T) {
		obj := &EvaluateContentResponse{}
		var fernTestValueResult map[string]any
		obj.SetResult(fernTestValueResult)
		assert.Equal(t, fernTestValueResult, obj.Result)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersEvaluateContentResponse(t *testing.T) {
	t.Run("GetResult", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvaluateContentResponse{}
		var expected map[string]any
		obj.Result = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetResult(), "getter should return the property value")
	})

	t.Run("GetResult_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvaluateContentResponse{}
		obj.Result = nil

		// Act & Assert
		assert.Nil(t, obj.GetResult(), "getter should return nil when property is nil")
	})

	t.Run("GetResult_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvaluateContentResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetResult() // Should return zero value
	})

}

func TestSettersMarkExplicitEvaluateContentResponse(t *testing.T) {
	t.Run("SetResult_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvaluateContentResponse{}
		var fernTestValueResult map[string]any

		// Act
		obj.SetResult(fernTestValueResult)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestGettersEvaluatorRequestContent(t *testing.T) {
	t.Run("GetString", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvaluatorRequestContent{}
		var expected string
		obj.String = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetString(), "getter should return the property value")
	})

	t.Run("GetString_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvaluatorRequestContent
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetString() // Should return zero value
	})

	t.Run("GetUnknownList", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvaluatorRequestContent{}
		var expected []any
		obj.UnknownList = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUnknownList(), "getter should return the property value")
	})

	t.Run("GetUnknownList_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvaluatorRequestContent{}
		obj.UnknownList = nil

		// Act & Assert
		assert.Nil(t, obj.GetUnknownList(), "getter should return nil when property is nil")
	})

	t.Run("GetUnknownList_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvaluatorRequestContent
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUnknownList() // Should return zero value
	})

}

func TestSettersGetEvaluationResponse(t *testing.T) {
	t.Run("SetData", func(t *testing.T) {
		obj := &GetEvaluationResponse{}
		var fernTestValueData map[string]any
		obj.SetData(fernTestValueData)
		assert.Equal(t, fernTestValueData, obj.Data)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersGetEvaluationResponse(t *testing.T) {
	t.Run("GetData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetEvaluationResponse{}
		var expected map[string]any
		obj.Data = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetData(), "getter should return the property value")
	})

	t.Run("GetData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetEvaluationResponse{}
		obj.Data = nil

		// Act & Assert
		assert.Nil(t, obj.GetData(), "getter should return nil when property is nil")
	})

	t.Run("GetData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetEvaluationResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetData() // Should return zero value
	})

}

func TestSettersMarkExplicitGetEvaluationResponse(t *testing.T) {
	t.Run("SetData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetEvaluationResponse{}
		var fernTestValueData map[string]any

		// Act
		obj.SetData(fernTestValueData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListEvaluationsResponse(t *testing.T) {
	t.Run("SetData", func(t *testing.T) {
		obj := &ListEvaluationsResponse{}
		var fernTestValueData []map[string]any
		obj.SetData(fernTestValueData)
		assert.Equal(t, fernTestValueData, obj.Data)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTotal", func(t *testing.T) {
		obj := &ListEvaluationsResponse{}
		var fernTestValueTotal *int
		obj.SetTotal(fernTestValueTotal)
		assert.Equal(t, fernTestValueTotal, obj.Total)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPage", func(t *testing.T) {
		obj := &ListEvaluationsResponse{}
		var fernTestValuePage *int
		obj.SetPage(fernTestValuePage)
		assert.Equal(t, fernTestValuePage, obj.Page)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPerPage", func(t *testing.T) {
		obj := &ListEvaluationsResponse{}
		var fernTestValuePerPage *int
		obj.SetPerPage(fernTestValuePerPage)
		assert.Equal(t, fernTestValuePerPage, obj.PerPage)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersListEvaluationsResponse(t *testing.T) {
	t.Run("GetData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsResponse{}
		var expected []map[string]any
		obj.Data = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetData(), "getter should return the property value")
	})

	t.Run("GetData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsResponse{}
		obj.Data = nil

		// Act & Assert
		assert.Nil(t, obj.GetData(), "getter should return nil when property is nil")
	})

	t.Run("GetData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListEvaluationsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetData() // Should return zero value
	})

	t.Run("GetTotal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsResponse{}
		var expected *int
		obj.Total = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTotal(), "getter should return the property value")
	})

	t.Run("GetTotal_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsResponse{}
		obj.Total = nil

		// Act & Assert
		assert.Nil(t, obj.GetTotal(), "getter should return nil when property is nil")
	})

	t.Run("GetTotal_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListEvaluationsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTotal() // Should return zero value
	})

	t.Run("GetPage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsResponse{}
		var expected *int
		obj.Page = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPage(), "getter should return the property value")
	})

	t.Run("GetPage_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsResponse{}
		obj.Page = nil

		// Act & Assert
		assert.Nil(t, obj.GetPage(), "getter should return nil when property is nil")
	})

	t.Run("GetPage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListEvaluationsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPage() // Should return zero value
	})

	t.Run("GetPerPage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsResponse{}
		var expected *int
		obj.PerPage = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPerPage(), "getter should return the property value")
	})

	t.Run("GetPerPage_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsResponse{}
		obj.PerPage = nil

		// Act & Assert
		assert.Nil(t, obj.GetPerPage(), "getter should return nil when property is nil")
	})

	t.Run("GetPerPage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListEvaluationsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPerPage() // Should return zero value
	})

}

func TestSettersMarkExplicitListEvaluationsResponse(t *testing.T) {
	t.Run("SetData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsResponse{}
		var fernTestValueData []map[string]any

		// Act
		obj.SetData(fernTestValueData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTotal_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsResponse{}
		var fernTestValueTotal *int

		// Act
		obj.SetTotal(fernTestValueTotal)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsResponse{}
		var fernTestValuePage *int

		// Act
		obj.SetPage(fernTestValuePage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPerPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsResponse{}
		var fernTestValuePerPage *int

		// Act
		obj.SetPerPage(fernTestValuePerPage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingEvaluateContentResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvaluateContentResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled EvaluateContentResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj EvaluateContentResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj EvaluateContentResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingGetEvaluationResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetEvaluationResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled GetEvaluationResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj GetEvaluationResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj GetEvaluationResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingListEvaluationsResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListEvaluationsResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ListEvaluationsResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ListEvaluationsResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ListEvaluationsResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringEvaluateContentResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &EvaluateContentResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvaluateContentResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringGetEvaluationResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &GetEvaluationResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetEvaluationResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringListEvaluationsResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ListEvaluationsResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListEvaluationsResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumEvaluatorRequestReasoningEffort(t *testing.T) {
	t.Run("NewFromString_low", func(t *testing.T) {
		t.Parallel()
		val, err := NewEvaluatorRequestReasoningEffortFromString("low")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, EvaluatorRequestReasoningEffort("low"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_medium", func(t *testing.T) {
		t.Parallel()
		val, err := NewEvaluatorRequestReasoningEffortFromString("medium")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, EvaluatorRequestReasoningEffort("medium"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_high", func(t *testing.T) {
		t.Parallel()
		val, err := NewEvaluatorRequestReasoningEffortFromString("high")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, EvaluatorRequestReasoningEffort("high"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewEvaluatorRequestReasoningEffortFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewEvaluatorRequestReasoningEffortFromString("low")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumEvaluatorRequestVerbosity(t *testing.T) {
	t.Run("NewFromString_minimal", func(t *testing.T) {
		t.Parallel()
		val, err := NewEvaluatorRequestVerbosityFromString("minimal")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, EvaluatorRequestVerbosity("minimal"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_low", func(t *testing.T) {
		t.Parallel()
		val, err := NewEvaluatorRequestVerbosityFromString("low")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, EvaluatorRequestVerbosity("low"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_medium", func(t *testing.T) {
		t.Parallel()
		val, err := NewEvaluatorRequestVerbosityFromString("medium")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, EvaluatorRequestVerbosity("medium"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_high", func(t *testing.T) {
		t.Parallel()
		val, err := NewEvaluatorRequestVerbosityFromString("high")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, EvaluatorRequestVerbosity("high"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewEvaluatorRequestVerbosityFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewEvaluatorRequestVerbosityFromString("minimal")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesEvaluateContentResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &EvaluateContentResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvaluateContentResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesGetEvaluationResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &GetEvaluationResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetEvaluationResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesListEvaluationsResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ListEvaluationsResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListEvaluationsResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
