// Code generated by Fern. DO NOT EDIT.

package chat

import (
	context "context"
	http "net/http"

	apgsdkgo "github.com/apologist-project/apg-sdk-go"
	core "github.com/apologist-project/apg-sdk-go/core"
	internal "github.com/apologist-project/apg-sdk-go/internal"
	option "github.com/apologist-project/apg-sdk-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) ListChatCompletions(
	ctx context.Context,
	request *apgsdkgo.ListChatCompletionsRequest,
	opts ...option.RequestOption,
) (*core.Response[*apgsdkgo.ListChatCompletionsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://your-agent-domain.com/api/v1",
	)
	endpointURL := baseURL + "/chat/completions"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *apgsdkgo.ListChatCompletionsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(apgsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*apgsdkgo.ListChatCompletionsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateChatCompletion(
	ctx context.Context,
	request *apgsdkgo.ChatCompletionRequest,
	opts ...option.RequestOption,
) (*core.Response[*apgsdkgo.ChatCompletionResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://your-agent-domain.com/api/v1",
	)
	endpointURL := baseURL + "/chat/completions"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *apgsdkgo.ChatCompletionResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(apgsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*apgsdkgo.ChatCompletionResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) LikeCompletion(
	ctx context.Context,
	request *apgsdkgo.LikeRequest,
	opts ...option.RequestOption,
) (*core.Response[*apgsdkgo.SuccessResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://your-agent-domain.com/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/chat/completions/%v/like",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *apgsdkgo.SuccessResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(apgsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*apgsdkgo.SuccessResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) FlagCompletion(
	ctx context.Context,
	request *apgsdkgo.FlagRequest,
	opts ...option.RequestOption,
) (*core.Response[*apgsdkgo.SuccessResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://your-agent-domain.com/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/chat/completions/%v/flag",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *apgsdkgo.SuccessResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(apgsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*apgsdkgo.SuccessResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) FeedbackCompletion(
	ctx context.Context,
	request *apgsdkgo.FeedbackRequest,
	opts ...option.RequestOption,
) (*core.Response[*apgsdkgo.SuccessResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://your-agent-domain.com/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/chat/completions/%v/feedback",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *apgsdkgo.SuccessResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(apgsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*apgsdkgo.SuccessResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ShareCompletion(
	ctx context.Context,
	request *apgsdkgo.ShareRequest,
	opts ...option.RequestOption,
) (*core.Response[*apgsdkgo.SuccessResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://your-agent-domain.com/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/chat/completions/%v/share",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *apgsdkgo.SuccessResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(apgsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*apgsdkgo.SuccessResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetChatCompletion(
	ctx context.Context,
	request *apgsdkgo.GetChatCompletionRequest,
	opts ...option.RequestOption,
) (*core.Response[*apgsdkgo.GetChatCompletionResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://your-agent-domain.com/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/chat/completions/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *apgsdkgo.GetChatCompletionResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(apgsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*apgsdkgo.GetChatCompletionResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
