// Code generated by Fern. DO NOT EDIT.

package conversations

import (
	context "context"

	apgsdkgo "github.com/apologist-project/apg-sdk-go"
	core "github.com/apologist-project/apg-sdk-go/core"
	internal "github.com/apologist-project/apg-sdk-go/internal"
	option "github.com/apologist-project/apg-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns a paginated list of conversations for the requesting agent, newest first.
//
// Example:
//
//	request := &apgsdkgo.ListConversationsRequest{}
//	client.Conversations.ListConversations(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListConversations(
	ctx context.Context,
	request *apgsdkgo.ListConversationsRequest,
	opts ...option.RequestOption,
) (*apgsdkgo.ListConversationsResponse, error) {
	response, err := c.WithRawResponse.ListConversations(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns a single conversation by internal UUID or team-scoped external id.
//
// Example:
//
//	request := &apgsdkgo.GetConversationRequest{
//	    ID: "id",
//	}
//	client.Conversations.GetConversation(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetConversation(
	ctx context.Context,
	request *apgsdkgo.GetConversationRequest,
	opts ...option.RequestOption,
) (*apgsdkgo.GetConversationResponse, error) {
	response, err := c.WithRawResponse.GetConversation(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Pauses the agent on a conversation identified by internal UUID or team-scoped external id. Requires an API key.
//
// Example:
//
//	request := &apgsdkgo.PauseConversationRequest{
//	    ID: "id",
//	}
//	client.Conversations.PauseConversation(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) PauseConversation(
	ctx context.Context,
	request *apgsdkgo.PauseConversationRequest,
	opts ...option.RequestOption,
) (*apgsdkgo.PauseConversationResponse, error) {
	response, err := c.WithRawResponse.PauseConversation(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Resumes the agent on a conversation identified by internal UUID or team-scoped external id. Requires an API key.
//
// Example:
//
//	request := &apgsdkgo.ResumeConversationRequest{
//	    ID: "id",
//	}
//	client.Conversations.ResumeConversation(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ResumeConversation(
	ctx context.Context,
	request *apgsdkgo.ResumeConversationRequest,
	opts ...option.RequestOption,
) (*apgsdkgo.ResumeConversationResponse, error) {
	response, err := c.WithRawResponse.ResumeConversation(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
