// Code generated by Fern. DO NOT EDIT.

package users

import (
	context "context"
	http "net/http"

	apgsdkgo "github.com/apologist-project/apg-sdk-go"
	core "github.com/apologist-project/apg-sdk-go/core"
	internal "github.com/apologist-project/apg-sdk-go/internal"
	option "github.com/apologist-project/apg-sdk-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) ListUsers(
	ctx context.Context,
	request *apgsdkgo.ListUsersRequest,
	opts ...option.RequestOption,
) (*core.Response[*apgsdkgo.ListUsersResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://your-agent-domain.com/api/v1",
	)
	endpointURL := baseURL + "/users"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *apgsdkgo.ListUsersResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(apgsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*apgsdkgo.ListUsersResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ListUserFlags(
	ctx context.Context,
	request *apgsdkgo.ListUserFlagsRequest,
	opts ...option.RequestOption,
) (*core.Response[*apgsdkgo.ListUserFlagsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://your-agent-domain.com/api/v1",
	)
	endpointURL := baseURL + "/users/flags"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *apgsdkgo.ListUserFlagsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(apgsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*apgsdkgo.ListUserFlagsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetUser(
	ctx context.Context,
	request *apgsdkgo.GetUserRequest,
	opts ...option.RequestOption,
) (*core.Response[*apgsdkgo.GetUserResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://your-agent-domain.com/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/users/%v",
		request.UserID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *apgsdkgo.GetUserResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(apgsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*apgsdkgo.GetUserResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) UpdateUser(
	ctx context.Context,
	request *apgsdkgo.UserUpdateRequest,
	opts ...option.RequestOption,
) (*core.Response[*apgsdkgo.UpdateUserResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://your-agent-domain.com/api/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/users/%v",
		request.UserID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *apgsdkgo.UpdateUserResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(apgsdkgo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*apgsdkgo.UpdateUserResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
