// Code generated by Fern. DO NOT EDIT.

package evaluators

import (
	context "context"

	apgsdkgo "github.com/apologist-project/apg-sdk-go"
	core "github.com/apologist-project/apg-sdk-go/core"
	internal "github.com/apologist-project/apg-sdk-go/internal"
	option "github.com/apologist-project/apg-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns a paginated list of evaluations for the evaluator, scoped to the requesting agent.
//
// Example:
//
//	request := &apgsdkgo.ListEvaluationsRequest{
//	    ID: "id",
//	}
//	client.Evaluators.ListEvaluations(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListEvaluations(
	ctx context.Context,
	request *apgsdkgo.ListEvaluationsRequest,
	opts ...option.RequestOption,
) (*apgsdkgo.ListEvaluationsResponse, error) {
	response, err := c.WithRawResponse.ListEvaluations(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Runs an evaluation on the provided content using the specified evaluator
//
// Example:
//
//	request := &apgsdkgo.EvaluatorRequest{
//	    ID: "id",
//	    Content: &apgsdkgo.EvaluatorRequestContent{
//	        String: "content",
//	    },
//	}
//	client.Evaluators.EvaluateContent(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) EvaluateContent(
	ctx context.Context,
	request *apgsdkgo.EvaluatorRequest,
	opts ...option.RequestOption,
) (*apgsdkgo.EvaluateContentResponse, error) {
	response, err := c.WithRawResponse.EvaluateContent(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns a single evaluation for the evaluator, scoped to the requesting agent.
//
// Example:
//
//	request := &apgsdkgo.GetEvaluationRequest{
//	    ID: "id",
//	    EvaluationID: "evaluationId",
//	}
//	client.Evaluators.GetEvaluation(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetEvaluation(
	ctx context.Context,
	request *apgsdkgo.GetEvaluationRequest,
	opts ...option.RequestOption,
) (*apgsdkgo.GetEvaluationResponse, error) {
	response, err := c.WithRawResponse.GetEvaluation(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
